package Entites;
// Generated 7 juin 2019 19:30:34 by Hibernate Tools 4.3.1



/**
 * Composant generated by hbm2java
 */
public class Composant  implements java.io.Serializable {


     private String numeroComposant;
     private String nomComposant;
     private String nomEtape;
     private String numeroEtape;

    public Composant() {
    }

    public Composant(String numeroComposant, String nomComposant, String nomEtape, String numeroEtape) {
       this.numeroComposant = numeroComposant;
       this.nomComposant = nomComposant;
       this.nomEtape = nomEtape;
       this.numeroEtape = numeroEtape;
    }
   
    public String getNumeroComposant() {
        return this.numeroComposant;
    }
    
    public void setNumeroComposant(String numeroComposant) {
        this.numeroComposant = numeroComposant;
    }
    public String getNomComposant() {
        return this.nomComposant;
    }
    
    public void setNomComposant(String nomComposant) {
        this.nomComposant = nomComposant;
    }
    public String getNomEtape() {
        return this.nomEtape;
    }
    
    public void setNomEtape(String nomEtape) {
        this.nomEtape = nomEtape;
    }
    public String getNumeroEtape() {
        return this.numeroEtape;
    }
    
    public void setNumeroEtape(String numeroEtape) {
        this.numeroEtape = numeroEtape;
    }




}


