package Entites;
// Generated 7 juin 2019 19:30:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Etape generated by hbm2java
 */
public class Etape  implements java.io.Serializable {


     private Integer idEtape;
     private Sousvariant sousvariant;
     private String nomEtape;
     private String numeroEtape;
     private String numSerieSousVariant;
     private String statutEtape;
     private Date tempsPrevuEtape;
     private int nombreOuvrier;

    public Etape() {
    }

    public Etape(Sousvariant sousvariant, String nomEtape, String numeroEtape, String numSerieSousVariant, String statutEtape, Date tempsPrevuEtape, int nombreOuvrier) {
       this.sousvariant = sousvariant;
       this.nomEtape = nomEtape;
       this.numeroEtape = numeroEtape;
       this.numSerieSousVariant = numSerieSousVariant;
       this.statutEtape = statutEtape;
       this.tempsPrevuEtape = tempsPrevuEtape;
       this.nombreOuvrier = nombreOuvrier;
    }
   
    public Integer getIdEtape() {
        return this.idEtape;
    }
    
    public void setIdEtape(Integer idEtape) {
        this.idEtape = idEtape;
    }
    public Sousvariant getSousvariant() {
        return this.sousvariant;
    }
    
    public void setSousvariant(Sousvariant sousvariant) {
        this.sousvariant = sousvariant;
    }
    public String getNomEtape() {
        return this.nomEtape;
    }
    
    public void setNomEtape(String nomEtape) {
        this.nomEtape = nomEtape;
    }
    public String getNumeroEtape() {
        return this.numeroEtape;
    }
    
    public void setNumeroEtape(String numeroEtape) {
        this.numeroEtape = numeroEtape;
    }
    public String getNumSerieSousVariant() {
        return this.numSerieSousVariant;
    }
    
    public void setNumSerieSousVariant(String numSerieSousVariant) {
        this.numSerieSousVariant = numSerieSousVariant;
    }
    public String getStatutEtape() {
        return this.statutEtape;
    }
    
    public void setStatutEtape(String statutEtape) {
        this.statutEtape = statutEtape;
    }
    public Date getTempsPrevuEtape() {
        return this.tempsPrevuEtape;
    }
    
    public void setTempsPrevuEtape(Date tempsPrevuEtape) {
        this.tempsPrevuEtape = tempsPrevuEtape;
    }
    public int getNombreOuvrier() {
        return this.nombreOuvrier;
    }
    
    public void setNombreOuvrier(int nombreOuvrier) {
        this.nombreOuvrier = nombreOuvrier;
    }




}


