package Entites;
// Generated 7 juin 2019 19:30:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Projet generated by hbm2java
 */
public class Projet  implements java.io.Serializable {


     private String numeroSerie;
     private String nomProjet;
     private Set variants = new HashSet(0);

    public Projet() {
    }

	
    public Projet(String numeroSerie, String nomProjet) {
        this.numeroSerie = numeroSerie;
        this.nomProjet = nomProjet;
    }
    public Projet(String numeroSerie, String nomProjet, Set variants) {
       this.numeroSerie = numeroSerie;
       this.nomProjet = nomProjet;
       this.variants = variants;
    }
   
    public String getNumeroSerie() {
        return this.numeroSerie;
    }
    
    public void setNumeroSerie(String numeroSerie) {
        this.numeroSerie = numeroSerie;
    }
    public String getNomProjet() {
        return this.nomProjet;
    }
    
    public void setNomProjet(String nomProjet) {
        this.nomProjet = nomProjet;
    }
    public Set getVariants() {
        return this.variants;
    }
    
    public void setVariants(Set variants) {
        this.variants = variants;
    }




}


