package Entites;
// Generated 7 juin 2019 19:30:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sousvariant generated by hbm2java
 */
public class Sousvariant  implements java.io.Serializable {


     private String nomSousVariant;
     private Variant variant;
     private String numSerieSousVariant;
     private String nomVariant;
     private int quantite;
     private int codeBarre;
     private Date dateEditionOrdre;
     private Date datePrevu;
     private String statut;
     private Set etapes = new HashSet(0);

    public Sousvariant() {
    }

	
    public Sousvariant(String nomSousVariant, Variant variant, String numSerieSousVariant, String nomVariant, int quantite, int codeBarre, Date dateEditionOrdre, Date datePrevu, String statut) {
        this.nomSousVariant = nomSousVariant;
        this.variant = variant;
        this.numSerieSousVariant = numSerieSousVariant;
        this.nomVariant = nomVariant;
        this.quantite = quantite;
        this.codeBarre = codeBarre;
        this.dateEditionOrdre = dateEditionOrdre;
        this.datePrevu = datePrevu;
        this.statut = statut;
    }
    public Sousvariant(String nomSousVariant, Variant variant, String numSerieSousVariant, String nomVariant, int quantite, int codeBarre, Date dateEditionOrdre, Date datePrevu, String statut, Set etapes) {
       this.nomSousVariant = nomSousVariant;
       this.variant = variant;
       this.numSerieSousVariant = numSerieSousVariant;
       this.nomVariant = nomVariant;
       this.quantite = quantite;
       this.codeBarre = codeBarre;
       this.dateEditionOrdre = dateEditionOrdre;
       this.datePrevu = datePrevu;
       this.statut = statut;
       this.etapes = etapes;
    }
   
    public String getNomSousVariant() {
        return this.nomSousVariant;
    }
    
    public void setNomSousVariant(String nomSousVariant) {
        this.nomSousVariant = nomSousVariant;
    }
    public Variant getVariant() {
        return this.variant;
    }
    
    public void setVariant(Variant variant) {
        this.variant = variant;
    }
    public String getNumSerieSousVariant() {
        return this.numSerieSousVariant;
    }
    
    public void setNumSerieSousVariant(String numSerieSousVariant) {
        this.numSerieSousVariant = numSerieSousVariant;
    }
    public String getNomVariant() {
        return this.nomVariant;
    }
    
    public void setNomVariant(String nomVariant) {
        this.nomVariant = nomVariant;
    }
    public int getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(int quantite) {
        this.quantite = quantite;
    }
    public int getCodeBarre() {
        return this.codeBarre;
    }
    
    public void setCodeBarre(int codeBarre) {
        this.codeBarre = codeBarre;
    }
    public Date getDateEditionOrdre() {
        return this.dateEditionOrdre;
    }
    
    public void setDateEditionOrdre(Date dateEditionOrdre) {
        this.dateEditionOrdre = dateEditionOrdre;
    }
    public Date getDatePrevu() {
        return this.datePrevu;
    }
    
    public void setDatePrevu(Date datePrevu) {
        this.datePrevu = datePrevu;
    }
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }
    public Set getEtapes() {
        return this.etapes;
    }
    
    public void setEtapes(Set etapes) {
        this.etapes = etapes;
    }




}


