package Entites;
// Generated 7 juin 2019 19:30:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Supervision generated by hbm2java
 */
public class Supervision  implements java.io.Serializable {


     private Integer idSuperviseur;
     private String numeroProjet;
     private String nomProjet;
     private String numeroVariant;
     private String nomVariant;
     private String numeroSousvariant;
     private String nomSousvariant;
     private int codeBarre;
     private int quantiteDemande;
     private String responsable;
     private Date dateEditionOrdre;
     private Date datePrevu;
     private String statutEtape;
     private String nomEtape;
     private int quantiteProduiteEtape;
     private Date dateActuelleScan;
     private Date dateDebutProduction;
     private String statutSousvariant;

    public Supervision() {
    }

    public Supervision(String numeroProjet, String nomProjet, String numeroVariant, String nomVariant, String numeroSousvariant, String nomSousvariant, int codeBarre, int quantiteDemande, String responsable, Date dateEditionOrdre, Date datePrevu, String statutEtape, String nomEtape, int quantiteProduiteEtape, Date dateActuelleScan, Date dateDebutProduction, String statutSousvariant) {
       this.numeroProjet = numeroProjet;
       this.nomProjet = nomProjet;
       this.numeroVariant = numeroVariant;
       this.nomVariant = nomVariant;
       this.numeroSousvariant = numeroSousvariant;
       this.nomSousvariant = nomSousvariant;
       this.codeBarre = codeBarre;
       this.quantiteDemande = quantiteDemande;
       this.responsable = responsable;
       this.dateEditionOrdre = dateEditionOrdre;
       this.datePrevu = datePrevu;
       this.statutEtape = statutEtape;
       this.nomEtape = nomEtape;
       this.quantiteProduiteEtape = quantiteProduiteEtape;
       this.dateActuelleScan = dateActuelleScan;
       this.dateDebutProduction = dateDebutProduction;
       this.statutSousvariant = statutSousvariant;
    }
   
    public Integer getIdSuperviseur() {
        return this.idSuperviseur;
    }
    
    public void setIdSuperviseur(Integer idSuperviseur) {
        this.idSuperviseur = idSuperviseur;
    }
    public String getNumeroProjet() {
        return this.numeroProjet;
    }
    
    public void setNumeroProjet(String numeroProjet) {
        this.numeroProjet = numeroProjet;
    }
    public String getNomProjet() {
        return this.nomProjet;
    }
    
    public void setNomProjet(String nomProjet) {
        this.nomProjet = nomProjet;
    }
    public String getNumeroVariant() {
        return this.numeroVariant;
    }
    
    public void setNumeroVariant(String numeroVariant) {
        this.numeroVariant = numeroVariant;
    }
    public String getNomVariant() {
        return this.nomVariant;
    }
    
    public void setNomVariant(String nomVariant) {
        this.nomVariant = nomVariant;
    }
    public String getNumeroSousvariant() {
        return this.numeroSousvariant;
    }
    
    public void setNumeroSousvariant(String numeroSousvariant) {
        this.numeroSousvariant = numeroSousvariant;
    }
    public String getNomSousvariant() {
        return this.nomSousvariant;
    }
    
    public void setNomSousvariant(String nomSousvariant) {
        this.nomSousvariant = nomSousvariant;
    }
    public int getCodeBarre() {
        return this.codeBarre;
    }
    
    public void setCodeBarre(int codeBarre) {
        this.codeBarre = codeBarre;
    }
    public int getQuantiteDemande() {
        return this.quantiteDemande;
    }
    
    public void setQuantiteDemande(int quantiteDemande) {
        this.quantiteDemande = quantiteDemande;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    public Date getDateEditionOrdre() {
        return this.dateEditionOrdre;
    }
    
    public void setDateEditionOrdre(Date dateEditionOrdre) {
        this.dateEditionOrdre = dateEditionOrdre;
    }
    public Date getDatePrevu() {
        return this.datePrevu;
    }
    
    public void setDatePrevu(Date datePrevu) {
        this.datePrevu = datePrevu;
    }
    public String getStatutEtape() {
        return this.statutEtape;
    }
    
    public void setStatutEtape(String statutEtape) {
        this.statutEtape = statutEtape;
    }
    public String getNomEtape() {
        return this.nomEtape;
    }
    
    public void setNomEtape(String nomEtape) {
        this.nomEtape = nomEtape;
    }
    public int getQuantiteProduiteEtape() {
        return this.quantiteProduiteEtape;
    }
    
    public void setQuantiteProduiteEtape(int quantiteProduiteEtape) {
        this.quantiteProduiteEtape = quantiteProduiteEtape;
    }
    public Date getDateActuelleScan() {
        return this.dateActuelleScan;
    }
    
    public void setDateActuelleScan(Date dateActuelleScan) {
        this.dateActuelleScan = dateActuelleScan;
    }
    public Date getDateDebutProduction() {
        return this.dateDebutProduction;
    }
    
    public void setDateDebutProduction(Date dateDebutProduction) {
        this.dateDebutProduction = dateDebutProduction;
    }
    public String getStatutSousvariant() {
        return this.statutSousvariant;
    }
    
    public void setStatutSousvariant(String statutSousvariant) {
        this.statutSousvariant = statutSousvariant;
    }




}


